### ISSUE TITLE
bug：if (document.getElementById("gitcalendarcanvasbox").offsetWidth < 500) {

### ISSUE THREAD

**Issue by cxvh** [TszHong0411/blog#1]
这个代码只有在首页不报错，
```js
//手機版更換為svg繪制
if (document.getElementById("gitcalendarcanvasbox").offsetWidth < 500) {
  gitcalendar.simplemode = false
}
```
解决方法如下
```js
//手機版更換為svg繪制
let gitcalendarcanvasbox= document.getElementById("gitcalendarcanvasbox")
if (gitcalendarcanvasbox&&gitcalendarcanvasbox.offsetWidth < 500) {
  gitcalendar.simplemode = false
}
```

**Comment by TszHong0411** [comment]
Oh！ 我现在才看到呀！我试一下，谢谢您！ε٩(๑> ₃ <)۶з

**Comment by TszHong0411** [comment]
> 这个代码只有在首页不报错，
> 
> ```js
> //手機版更換為svg繪制
> if (document.getElementById("gitcalendarcanvasbox").offsetWidth < 500) {
>   gitcalendar.simplemode = false
> }
> ```
> 
> 解决方法如下
> 
> ```js
> //手機版更換為svg繪制
> let gitcalendarcanvasbox= document.getElementById("gitcalendarcanvasbox")
> if (gitcalendarcanvasbox&&gitcalendarcanvasbox.offsetWidth < 500) {
>   gitcalendar.simplemode = false
> }
> ```

可以了～～
